experimentalTernaries: false
printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
# rangeStart: 0
# rangeEnd: Infinity
endOfLine: lf
singleAttributePerLine: false
